import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Regalo Nascita Santiago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center w-screen h-screen">
        <h1>Santiago is coming</h1>
      </main>

      <footer></footer>
    </div>
  )
}
