import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Regalo Nascita Santiago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center align-middle items-center w-screen h-screen flex-col container_born">
        <div className="lineTop"></div>
        <div className="boxText">
          <h1 className=" text-5xl flex">Ciao sono Santiago,</h1>
          <p className=" text-md flex mt-3">
            siccome ho già capito che<br></br> i miei gienitori sono poco
            affidabili,<br></br> conto su di voi...<br></br>
          </p>
          <h1 className=" text-5xl flex mt-10">Come?</h1>
          <p className=" text-md flex mt-3">Con una piccola donazione.</p>
          <p className=" text-md flex mt-3">Vedrò poi, giorno dopo giorno,</p>
          <p className=" text-md flex">di cosa avrò davvero bisogno.</p>
          <p className=" text-md flex mt-10">
            Intestatari: Zamberoni Selene, Volpi Nicola
          </p>
          <p className="text-md flex">Causale: Regalo di nascita</p>
          <p className=" text-md flex">IBAN: IT76D0306924888100000012156</p>
        </div>
        <div className="lineBottom"></div>
      </main>

      <footer></footer>
    </div>
  )
}
